In [31]:

# Importing pandas library
import pandas as pd

# Importing numpy library
import numpy as np

In [32]:

# Creating Employee DataFrame
employee = pd.DataFrame({

    # Creating ID column
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'],

    # Creating Name column
    'Name': ['John Alter', 'Alice Luxumberg', 'Tom Sabestine', 'Nina Adgra', 'Amy Johny'],

     # Creating Gender column
    'Gender': ['M', 'F', 'M', 'F', 'F'],

     # Creating Gender column
    'City': ['Paris', 'London', 'Berlin', 'Newyork', 'Madrid'],

    # Creating Age column
    'Age': [25, 27, 29, 31, 30]
})

# Displaying employee dataframe
employee

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [33]:

# Creating Seniority Level DataFrame
seniority = pd.DataFrame({

    # Creating ID column
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'],

    # Creating Designation Level column
    'Designation Level': [2, 2, 3, 2, 3]
})

# Displaying seniority dataframe
seniority

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [34]:

# Creating Project DataFrame
project = pd.DataFrame({

     # Creating ID column
    'ID': ['A001','A002','A003','A004','A005','A002','A005','A003','A001','A003','A001','A004','A004','A005'],

     # Creating Project column
     'Project': ['Project 1','Project 2','Project 3','Project 4','Project 5','Project 6','Project 7','Project 8','Project 9','Project 10','Project 11','Project 12','Project 13','Project 14'],

      # Creating Cost column with missing values
     'Cost': [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,np.nan,300000,2000000,1000000,3000000,200000],

     # Creating Status column
     'Status': ['Finished','Ongoing','Finished','Ongoing','Finished','Failed','Finished','Failed','Ongoing','Finished','Failed','Ongoing','Finished','Finished']
})

# Displaying project dataframe
project

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [35]:

# Saving employee dataframe as CSV file
employee.to_csv('employee.csv', index=False)

# Saving seniority dataframe as CSV file
seniority.to_csv('seniority.csv', index=False)

# Saving project dataframe as CSV file
project.to_csv('project.csv', index=False)

In [36]:

# Reading project CSV file
proj = pd.read_csv('project.csv')

# Initializing total variable
total = 0

# Initializing count variable
count = 0

# Running loop through project dataframe
for i in range(len(proj)):

    # Checking if cost value is not missing
    if not pd.isna(proj.loc[i, 'Cost']):

        # Adding existing cost to total
        total += proj.loc[i, 'Cost']

        # Increasing count
        count += 1

     # Executing if value is missing
    else:

        # Replacing missing value with running average
        proj.loc[i, 'Cost'] = total / count

# Displaying updated dataframe
proj

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [37]:


# Saving updated project dataframe
proj.to_csv('project.csv', index=False)

In [38]:

# Reading employee CSV file
emp = pd.read_csv('employee.csv')

# Splitting Name column into First Name and Last Name
emp[['First Name', 'Last Name']] = emp['Name'].str.split(' ', expand=True)

# Dropping original Name colum
emp.drop('Name', axis=1, inplace=True)

# Displaying employee dataframe
emp

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [39]:

# Reading seniority CSV file
sen = pd.read_csv('seniority.csv')


# Reading updated project CSV file
proj = pd.read_csv('project.csv')

# Merging employee dataframe and seniority dataframe
df1 = pd.merge(emp, sen, on='ID')

# Merging project dataframe with previous merged dataframe
final = pd.merge(df1, proj, on='ID')

# Display final dataframe
final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished

In [40]:

# Adding Bonus column for finished projects
final['Bonus'] = np.where(final['Status'] == 'Finished',
                         final['Cost'] * 0.05, 0)

# Displaying final dataframe
final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [41]:

# Increase designation level for failed projects
final.loc[final['Status'] == 'Failed', 'Designation Level'] += 1

# Remove employees with designation level > 4
final = final[final['Designation Level'] <= 4]

# Displaying updated dataframe
final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [42]:

# Defining function to add title
def add_title(row):

      # Checking male gender
    if row['Gender'] == 'M':

        # Adding Mr. before first name
        return 'Mr. ' + row['First Name']
    else:

        # Adding Mrs. before first name
        return 'Mrs. ' + row['First Name']

# Applying function on First Name column
final['First Name'] = final.apply(add_title, axis=1)

# Dropping Gender column
final.drop('Gender', axis=1, inplace=True)

# Displaying updated dataframe
final

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [43]:


# Promoting employees whose age is greater than 29
final.loc[final['Age'] > 29, 'Designation Level'] -= 1

# Ensuring designation level does not go below 1
final.loc[final['Designation Level'] < 1, 'Designation Level'] = 1

# Displaying updated dataframe
final

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,2,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,2,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,2,Project 14,2.000000e+05,Finished,10000.0

In [44]:

# Grouping dataframe by ID and First Name
total_cost = final.groupby(['ID', 'First Name'])['Cost'].sum().reset_index()

# Renaming Cost column to Total Cost
total_cost.rename(columns={'Cost': 'Total Cost'}, inplace=True)

# Displaying total project cost dataframe
total_cost

     ID  First Name    Total Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

In [45]:

# Filtering employees whose city contains letter o
result = final[final['City'].str.contains('o', case=False)]

# Displaying filtered dataframe
result

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000.0,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,680000.0,Failed,0.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5500000.0,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1000000.0,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3000000.0,Finished,150000.0

In [46]:

# Saving final dataframe as CSV file
final.to_csv('final_output.csv', index=False)

# Saving total project cost dataframe as CSV file
total_cost.to_csv('total_project_cost.csv', index=False)